{
 "title": "Performance Dashboard",
 "description": "Nasuni Performance Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Customer",
    "label": "Customer",
    "query": "SHOW TAG VALUES FROM \"Nasuni\" WITH KEY = \"customer\""
   },
   {
    "name": "Region",
    "label": "Region",
    "query": "SHOW TAG VALUES FROM \"Nasuni\" WITH KEY = \"filer_location\" WHERE customer =~ /$Customer/"
   },
   {
    "name": "Appliance",
    "label": "Appliance",
    "query": "SHOW TAG VALUES FROM \"Nasuni\" WITH KEY = \"hostname\" WHERE customer =~ /$Customer/ AND filer_location =~ /$Region/"
   },
   {
    "name": "CacheDisk",
    "label": "CacheDisk",
    "query": "SELECT last(\"filer_device_cache\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/)"
   },
   {
    "name": "RootDisk",
    "label": "RootDisk",
    "query": "SELECT last(\"filer_device_root\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nasuni Licensed Capacity Total vs Used",
   "type": "stat",
   "description": "Total customer licensed capacity.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT mean(\"nasuni_account_license_capacity\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY ($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "nasuni_account_license_capacity"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT mean(\"nasuni_account_used_percentage\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "nasuni_account_used_percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "$Appliance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "Appliance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Platform",
   "type": "stat",
   "description": "Nasuni appliance platform type.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT last(\"filer_platform_name\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "filer_platform_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Nasuni software release version.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "select": [
      [
       { "params": [ "filer_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "The 1/5/15 minute load averages.",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "1Min Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT max(\"cpula1\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpula1" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    },
    {
     "alias": "5Min Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT max(\"cpula5\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpula5" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    },
    {
     "alias": "15Min Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "select": [
      [
       { "params": [ "cpula15" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Disk Load",
   "type": "timeseries",
   "description": "The 1/5/15 minute average load of disk (%).",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "1Min Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nasuni_disk",
     "query": "SELECT max(\"diskiola1\") FROM \"nasuni_disk\" WHERE (\"hostname\" =~ /^$Appliance$/ AND \"diskiodevice\" =~ /^$CacheDisk$/) AND $timeFilter GROUP BY time($__interval), \"diskiodevice\"",
     "select": [
      [
       { "params": [ "diskiola1" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    },
    {
     "alias": "5Min Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nasuni_disk",
     "query": "SELECT max(\"diskiola5\") FROM \"nasuni_disk\" WHERE (\"hostname\" =~ /^$Appliance$/ AND \"diskiodevice\" =~ /^$CacheDisk$/) AND $timeFilter GROUP BY time($__interval), \"diskiodevice\"",
     "select": [
      [
       { "params": [ "diskiola5" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    },
    {
     "alias": "15Min Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nasuni_disk",
     "query": "SELECT max(\"diskiola15\") FROM \"nasuni_disk\" WHERE (\"hostname\" =~ /^$Appliance$/ AND \"diskiodevice\" =~ /^$CacheDisk$/) AND $timeFilter GROUP BY time($__interval), \"diskiodevice\"",
     "select": [
      [
       { "params": [ "diskiola15" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "description": "Displays cache usage over time. Helpful for planning future cache size requirements.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total Cache Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT mean(\"filer_cache_total\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "filer_cache_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    },
    {
     "alias": "Total Cache Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT mean(\"filer_cache_used\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "filer_cache_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The amount of time since this host was last\ninitialized. (hrSystemUptime)",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT mean(\"filer_online\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "filer_version" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SMB Connections",
   "type": "stat",
   "description": "Number of connected SMB clients.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT last(\"filer_total_share_clients\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "filer_total_share_clients" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "% CPU utilization (1m).",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT last(\"cpu_idle\")  * -1 +100 FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "cpula1" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Shares",
   "type": "stat",
   "description": "The total number of active shares.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT last(\"filer_total_shares\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "filer_total_shares" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "description": "The total amount of real/physical memory installed\non this host and the amount of real/physical memory currently unused or available.",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT last(\"mem_total_real\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mem_total_real" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    },
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT last(\"mem_avail_real\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mem_avail_real" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Disk I/O",
   "type": "timeseries",
   "description": "The 1/5/15 minute max load of disk (%).",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "Max Read",
     "query": "SELECT non_negative_derivative(max(\"diskioreads\"), 10s) FROM \"nasuni_disk\" WHERE (\"hostname\" =~ /^$Appliance$/ AND \"diskiodevice\" =~ /^$CacheDisk$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Max Write",
     "query": "SELECT non_negative_derivative(max(\"diskiowrites\"), 10s) FROM \"nasuni_disk\" WHERE (\"hostname\" =~ /^$Appliance$/ AND \"diskiodevice\" =~ /^$CacheDisk$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "description": "Clients to Nasuni transmit/receive bits/second for the last 1 minute.\nNasuni to Cloud transmit/receive bits/second for the last 1 minute.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT max(\"filer_nw_clients_in\") AS \"Clients In\", max(\"filer_nw_clients_out\") AS \"Clients Out\", max(\"filer_nw_cloud_in\") AS \"Cloud In\", max(\"filer_nw_cloud_out\") AS \"Cloud Out\" FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "filer_nw_clients_in" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Clients In" ], "type": "alias" }
      ],
      [
       { "params": [ "filer_nw_clients_out" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Clients Out" ], "type": "alias" }
      ],
      [
       { "params": [ "filer_nw_cloud_in" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Cloud In" ], "type": "alias" }
      ],
      [
       { "params": [ "filer_nw_cloud_out" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Cloud Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Memory utilization.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT (last(\"mem_total_real\") - (last(\"mem_avail_real\") + last(\"mem_cached\"))) / last(\"mem_total_real\") * 100 FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "mem_total_real" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "mem_avail_real" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "File Locks",
   "type": "stat",
   "description": "Active number of open file locks.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT last(\"filer_total_share_locks\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "filer_total_share_locks" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "gauge",
   "description": "Cache utilization.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT (mean(\"filer_cache_used\") / mean(\"filer_cache_total\")) * 100 FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "filer_cache_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Unprotected Data",
   "type": "stat",
   "description": "Data that is yet to be snapped to your object storage provider.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Nasuni",
     "select": [
      [
       { "params": [ "filer_total_unprotected_data" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Tracks Linux memory usage. Both Cached and Buffered memory normally show as used, but are available for the OS and Applications to use.",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Utilized",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT (last(\"mem_total_real\") - last(\"mem_avail_real\")) / last(\"mem_total_real\") * 100 FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "mem_total_real" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "mem_avail_real" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    },
    {
     "alias": "Cached (Available)",
     "query": "SELECT (last(\"mem_cached\"))/ last(\"mem_total_real\") * 100   FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time(10s) fill(null)"
    },
    {
     "alias": "Buffered (Available)",
     "query": "SELECT (last(\"mem_buffer\"))/ last(\"mem_total_real\") * 100   FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time(10s) fill(null)"
    }
   ]
  },
  {
   "title": "OS Disk Load",
   "type": "timeseries",
   "description": "The number of read & write accesses on this device since boot.",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "1Min Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nasuni_disk",
     "query": "SELECT max(\"diskiola1\") FROM \"nasuni_disk\" WHERE (\"hostname\" =~ /^$Appliance$/ AND \"diskiodevice\" =~ /^$RootDisk$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "diskioreads" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" },
      { "condition": "AND", "key": "diskiodevice", "operator": "=", "value": "nvme1n1" }
     ]
    },
    {
     "alias": "5Min Avg",
     "query": "SELECT max(\"diskiola5\") FROM \"nasuni_disk\" WHERE (\"hostname\" =~ /^$Appliance$/ AND \"diskiodevice\" =~ /^$RootDisk$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "15Min Avg",
     "query": "SELECT max(\"diskiola15\") FROM \"nasuni_disk\" WHERE (\"hostname\" =~ /^$Appliance$/ AND \"diskiodevice\" =~ /^$RootDisk$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "SMB Connections",
   "type": "timeseries",
   "description": "SMB connection count over time.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT last(\"filer_total_share_clients\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "filer_total_share_clients" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Activity",
   "type": "stat",
   "description": "This graph allows you to monitor cache activity in a little more detail.  eg What your % cache miss ratio looks like.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cache Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT last(\"filer_read_hits\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "filer_read_hits" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    },
    {
     "alias": "Cache Miss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT last(\"filer_read_misses\") FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "filer_read_hits" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    },
    {
     "alias": "Cache Miss %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Nasuni",
     "query": "SELECT last(\"filer_read_misses\") / (last(\"filer_read_hits\") + last(\"filer_read_misses\")) * 100 FROM \"Nasuni\" WHERE (\"hostname\" =~ /^$Appliance$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "filer_read_hits" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Appliance$/" }
     ]
    }
   ]
  }
 ]
}