{
 "title": "Nasuni Access Anywhere",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "show tag values with key = \"systemName\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Access Anywhere Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Online Users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "naaOnlineUsers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Total Users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "naaTotalUsers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Information",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Number of FIles",
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "naaFileCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Storage Under Management",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "naaStorageUnderMgmt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Org Providers",
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "naaOrgProviders" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Private Providers",
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "naaPrivateProviders" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Under Management",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "sum",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "naaStorageUnderMgmt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Links",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Shared Links",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "naaSharedLinks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "cpuIdle" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "*-1+100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Available %",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "query": "SELECT ((\"freeMem\" + \"cachedMem\")/\"totalMem\" * 100) FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) ",
       "select": [
        [
         { "params": [ "freeMem" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "cpuCores" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Services Running",
     "type": "stat",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Mysql",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "dbUptime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Memcache",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "memcacheUptime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "redis",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "uptime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Docker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_status",
       "select": [
        [
         { "params": [ "uptime_ns" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000000000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Root Used",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "SELECT (\"rootUsed\"/(\"rootFree\"+rootUsed) * 100) FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) AND $timeFilter ",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
       ]
      }
     ]
    },
    {
     "title": "Data Volume Used",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "SELECT (\"mysqlUsed\"/(\"mysqlFree\" +\"mysqlUsed\") * 100) FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) AND $timeFilter ",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$DataVolume$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "totalMem" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Frequency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "cpuFreq" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "*1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "systemUptime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "iowait",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "cpuIoWait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "user",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "cpuUser" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "system",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "cpuSystem" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "totalMem" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "free",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "freeMem" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "shared",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "sharedMem" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "cached",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "cachedMem" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "/ Disk Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Free Space",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "query": "SELECT mean(\"rootFree\") FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
       "select": [
        [
         { "params": [ "rootFree" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Used Space",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "rootUsed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Database Volume Usage ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Free Space",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "mysqlFree" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Used Space",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "mysqlUsed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Root Disk IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Read IOPS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "query": "SELECT \"reads\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "rootIOPSRead" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "WriteIOPS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "query": "SELECT \"reads\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "rootIOPSWrite" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "DB Disk IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Read IOPS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "query": "SELECT \"reads\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "mysqlIOPSRead" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "WriteIOPS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "query": "SELECT \"reads\" FROM \"diskio\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "mysqlIOPSWrite" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Iface Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Received Bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "netRecv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Sent Bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "naametrics",
       "select": [
        [
         { "params": [ "netSent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Database Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memcache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Get",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "query": "SELECT (last(\"memcacheGetHits\") / ( last(\"memcacheGetMisses\" ) + last(\"memcacheGetHits\"))) * 100 FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memcacheGetHits" ], "type": "field" }
      ],
      [
       { "params": [ "memcacheGetMisses" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Incr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"memcacheIncrHits\") / ( last(\"memcacheIncrMisses\" ) + last(\"memcacheIncrHits\"))) * 100 FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Delete",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memcached",
     "query": "SELECT (last(\"memcacheDeleteHits\") / ( last(\"memcacheDeleteMisses\" ) + last(\"memcacheDeleteHits\"))) * 100 FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "get_hits" ], "type": "field" }
      ],
      [
       { "params": [ "get_misses" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Cas",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memcached",
     "query": "SELECT (last(\"memcacheCasHits\") / ( last(\"memcacheCasMisses\" ) + last(\"memcacheCasHits\"))) * 100 FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "get_hits" ], "type": "field" }
      ],
      [
       { "params": [ "get_misses" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "DB Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Select",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "dbSelects" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Delete",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "dbDeletes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Insert",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "dbInserts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Update",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "dbUpdates" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Mysql Queries over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Slow Queries",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "query": "SELECT derivative(mean(\"dbSlowQueries\"), 1m) FROM \"naametrics\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dbSlowQueries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Deletes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "query": "SELECT derivative(mean(\"dbDeletes\"), 1m) FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dbDeletes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Inserts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "query": "SELECT derivative(mean(\"dbUpdates\"), 1m) FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dbInserts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Selects",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "query": "SELECT derivative(mean(\"dbSelects\"), 1m) FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dbSelects" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Updates",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "query": "SELECT derivative(mean(\"dbInserts\"), 1m) FROM \"naametrics\" WHERE (\"systemName\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dbUpdates" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Connection Info",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Mysql Connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "dbConnections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Slow Queries",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "dbSlowQueries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Table IO Wait Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Delete Waits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mysql_perf_schema",
     "select": [
      [
       { "params": [ "table_io_waits_total_delete" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Fetch Waits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mysql_perf_schema",
     "select": [
      [
       { "params": [ "table_io_waits_total_fetch" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Insert Waits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mysql_perf_schema",
     "select": [
      [
       { "params": [ "index_io_waits_total_insert" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Update Waits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mysql_perf_schema",
     "select": [
      [
       { "params": [ "table_io_waits_total_update" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Mysql Replication Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "IO Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "repIORunning" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "SQL Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "select": [
      [
       { "params": [ "repSQLRunning" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Mysql Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Seconds behind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "naametrics",
     "query": "SELECT derivative(mean(\"dbSlowQueries\"), 1m) FROM \"naametrics\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "repSecBehindMaster" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "systemName", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}